### ISSUE TITLE
Error parsing date

### ISSUE THREAD

**Issue by mmc46** [ontodev/robot#100]
Converting between owl and obo getting the error

ERROR MASKING ERROR «Could not parse date string: 2016-04-08»

Full output
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
ERROR MASKING ERROR «Could not parse date string: 2016-04-08»
java.lang.Exception
    at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
    at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:883)
    at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:1217)
    at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:254)
    at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
    at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:57)
    at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
    at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
    at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
    at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
    at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:443)
    at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:419)
    at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:143)
    at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
    at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
    at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
    at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:51)

**Comment by cmungall** [comment]
I think this is in the owlapi and not robot.

it's likely you're using a field like created_by that in obo format is very particular about the dateformat used, hard to say without seeing ontology

reopen with example if this is still a problem, thanks!
