### ISSUE TITLE
Robot explain crashes upon writing the explanations to Markdown

### ISSUE THREAD

**Issue by psiotwo** [ontodev/robot#1021]
The command 

`robot explain -vvv -i input.owl --reasoner ELK -M unsatisfiability --unsatisfiable all --explanation explanations.md`

command ends-up with the following exception (I will try to provide some MWE ontology to debug this).

```
21:14:13 DEBUG Missing exception ID: Comparison method violates its general contract!
21:14:45 Comparison method violates its general contract!
21:14:45 java.lang.IllegalArgumentException: Comparison method violates its general contract!
21:14:45 	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
21:14:45 	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
21:14:45 	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
21:14:45 	at java.base/java.util.TimSort.sort(TimSort.java:245)
21:14:45 	at java.base/java.util.Arrays.sort(Arrays.java:1515)
21:14:45 	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
21:14:45 	at java.base/java.util.Collections.sort(Collections.java:179)
21:14:45 	at uk.ac.manchester.cs.owl.explanation.ProtegeExplanationOrderer.getRHSEntitiesSorted(ProtegeExplanationOrderer.java:181)
21:14:45 	at uk.ac.manchester.cs.owl.explanation.ProtegeExplanationOrderer.insertChildren(ProtegeExplanationOrderer.java:212)
21:14:45 	at uk.ac.manchester.cs.owl.explanation.ProtegeExplanationOrderer.insertChildren(ProtegeExplanationOrderer.java:213)
21:14:45 	at uk.ac.manchester.cs.owl.explanation.ProtegeExplanationOrderer.insertChildren(ProtegeExplanationOrderer.java:213)
21:14:45 	at uk.ac.manchester.cs.owl.explanation.ProtegeExplanationOrderer.getOrderedExplanation(ProtegeExplanationOrderer.java:135)
21:14:45 	at org.obolibrary.robot.ExplainOperation.renderExplanationAsMarkdown(ExplainOperation.java:165)
21:14:45 	at org.obolibrary.robot.ExplainCommand.lambda$writeExplanationsToFile$5(ExplainCommand.java:292)
21:14:45 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
21:14:45 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
21:14:45 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
21:14:45 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
21:14:45 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
21:14:45 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
21:14:45 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
21:14:45 	at org.obolibrary.robot.ExplainCommand.writeExplanationsToFile(ExplainCommand.java:293)
21:14:45 	at org.obolibrary.robot.ExplainCommand.handleUnsatisfiableMode(ExplainCommand.java:199)
21:14:45 	at org.obolibrary.robot.ExplainCommand.execute(ExplainCommand.java:139)
21:14:45 	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
21:14:45 	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
21:14:45 	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
21:14:45 	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:61)
```

**Comment by matentzn** [comment]
Instead of all, try random:50. this May simply be too many unsats to write out.

**Comment by psiotwo** [comment]
Thanks for tip @matentzn, worked (but for nothing greater than 2 in my case ;-) )! 

I propose to keep the ticket open for improving the error message in this case.

**Comment by jamesaoverton** [comment]
@balhoff Any ideas about this one?

**Comment by balhoff** [comment]
Not offhand, but I could take a look at an example input that causes the problem.

**Comment by cmungall** [comment]
I was able to replicate this, see attached

Sorry the ontology is a bit crazy (it was made by ontogpt)

[expl-test.owl.gz.txt](https://github.com/ontodev/robot/files/10356065/expl-test.owl.gz.txt)

**Comment by psiotwo** [comment]
@cmungall thanks a lot, I actually completely forgot on this bit ...

Attached is a MUPS (or almost MUPS, didn't check) pinpointed from that ontology. 
[expl-test.owl.txt](https://github.com/ontodev/robot/files/10372151/expl-test.owl.txt)

**Comment by balhoff** [comment]
Since the same error happens in Protégé, the fix might need to be made in one of these:
- https://github.com/protegeproject/explanation-workbench
- https://github.com/matthewhorridge/owlexplanation
