### ISSUE TITLE
[1.9.0] Could not convert to OBO Graph

### ISSUE THREAD

**Issue by anitacaron** [ontodev/robot#1037]
I'm trying to update to 1.9.0 in Docker, but I can no longer convert OWL to JSON. I can convert it using version 1.8.2.

I'm getting this error:

```
OBO GRAPH ERROR Could not convert ontology to OBO Graph (see https://github.com/geneontology/obographs)
For details see: http://robot.obolibrary.org/errors#obo-graph-error
java.io.IOException: errors#OBO GRAPH ERROR Could not convert ontology to OBO Graph (see https://github.com/geneontology/obographs)
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1722)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:846)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:667)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:61)
```

This is the OWL file:

```
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)


Ontology(
Declaration(Class(<http://purl.obolibrary.org/obo/CL_1000308>))
Declaration(Class(<http://purl.obolibrary.org/obo/CL_1000708>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_0000056>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_0001253>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_0001254>))
Declaration(Class(<http://purl.obolibrary.org/obo/UBERON_0009919>))
Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000050>))



############################
#   Classes
############################

# Class: <http://purl.obolibrary.org/obo/CL_1000308> (fibrocyte of adventitia of ureter)

AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/CL_1000308> "fibrocyte of adventitia of ureter"^^xsd:string)
SubClassOf(<http://purl.obolibrary.org/obo/CL_1000308> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0000056>))

# Class: <http://purl.obolibrary.org/obo/CL_1000708> (ureter adventitial cell)

AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/CL_1000708> "ureter adventitial cell"^^xsd:string)
SubClassOf(<http://purl.obolibrary.org/obo/CL_1000708> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0000056>))

# Class: <http://purl.obolibrary.org/obo/UBERON_0000056> (ureter)

AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_0000056> "ureter"^^xsd:string)

# Class: <http://purl.obolibrary.org/obo/UBERON_0001253> (lamina propria of ureter)

AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_0001253> "lamina propria of ureter"^^xsd:string)
SubClassOf(<http://purl.obolibrary.org/obo/UBERON_0001253> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0000056>))

# Class: <http://purl.obolibrary.org/obo/UBERON_0001254> (urothelium of ureter)

AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_0001254> "urothelium of ureter"^^xsd:string)
SubClassOf(<http://purl.obolibrary.org/obo/UBERON_0001254> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0000056>))

# Class: <http://purl.obolibrary.org/obo/UBERON_0009919> (ureter smooth muscle)

AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/UBERON_0009919> "ureter smooth muscle"^^xsd:string)
SubClassOf(<http://purl.obolibrary.org/obo/UBERON_0009919> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0000056>))


)
```

**Comment by matentzn** [comment]
It does seem a bit brutal, but both obo and obographs-json formats (which was just updated, hence the failure) will fail if you do not provide an ontology IRI. This will work:

```
robot -vvv annotate -i data/obog-fail.owl --ontology-iri http://purl.obolibrary.org/obo/mondo.owl convert -f json -o failobog.json
```

If this is a really important issue for you make a ticket here: https://github.com/geneontology/obographs/issues
and elevate it in the obo-format channel in the OBO slack. I will close the issue now, but please reopen immediately if unsatisfied.

**Comment by anitacaron** [comment]
Thank you, Nico!
