### ISSUE TITLE
Integration test for extract subset failing in CI

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#1166]
See #1104 and recent Action results. The integration test here [docs/extract.md#subset](https://github.com/ontodev/robot/blob/master/docs/extract.md#subset) always passes for me locally, but it's failing 90% of the time on my runs for #1104. I really don't get it. I saw a "zio-fiber" error (?) in relationgraph on one run, but I can't find that message now.

Any ideas?

**Comment by jamesaoverton** [comment]
I saw that zio error again, this time in a unit test:

```
testExtractSubset(org.obolibrary.robot.ExtractOperationTest)  Time elapsed: 0.598 sec  <<< ERROR!
Error: Exception in thread "zio-fiber-19" java.lang.InterruptedException: Interrupted by thread "zio-fiber-19"
	at org.renci.relationgraph.RelationGraph.processRestrictionAndExtendQueue(RelationGraph.scala:131)
	at org.renci.relationgraph.RelationGraph.computeRelations.streamZ(RelationGraph.scala:75)
```

**Comment by jamesaoverton** [comment]
@balhoff I fixed my link to point to the first attempt of that run, which failed. I just re-ran it and then it worked.

Yes this is hard to debug, but also really disruptive to development workflows.

**Comment by jamesaoverton** [comment]
This issue is breaking CI for another (unrelated) PR: https://github.com/ontodev/robot/actions/runs/7107481969/job/19348979228#step:5:21700

I need a solution for this. The best I've got right now is to disable the test, which sucks.

**Comment by jamesaoverton** [comment]
Hopefully closed by https://github.com/ontodev/robot/pull/1174

**Comment by jamesaoverton** [comment]
I think this is still a problem. A large percentage of my CI runs have been failing, e.g. https://github.com/ontodev/robot/actions/runs/22157649265/job/64065844347#step:5:12256

I never see the problem locally.

```
Error:  Errors: 
Error:    ExtractOperationTest.testExtractSubset:175 » Interrupted
```

**Comment by balhoff** [comment]
@jamesaoverton I'm trying something in relation-graph. Hopefully I'll come back soon with a solution.
