### ISSUE TITLE
getting errors on fma.owl

### ISSUE THREAD

**Issue by maximilianh** [ontodev/robot#181]
I'm trying to convert the fma.owl file to .obo with this command:

robot convert -input fma.owl -output fma.obo

I'm using the most up-to-date FMA from here:
https://bioportal.bioontology.org/ontologies/FMA

And the most current robot command from https://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot.jar

However, I'm getting error messages like this:
```

ERROR Illegal redeclarations of entities: reuse of entity
http://purl.org/sig/ont/fma/has_direct_shape_type in punning not
allowed [Declaration(DataProperty(<http://purl.org
ERROR MASKING ERROR «the axiom is not translated :
SubClassOf(<http://purl.org/sig/ont/fma/fma23242>
ObjectSomeValuesFrom(<http://purl.org/sig/ont/fma/attributed_part>
Objec
java.lang.Exception
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:2047)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:259)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:57)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:468)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:432)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:144)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:55)
```

Can I somehow skip these error messages and get at least some part of the .obo file? Or is there an easy way to fix the FMA by removing the errors from the .owl ?

I also notice that no website seems to provide an .obo version of the .owl.

Is there another converter tool that you use in such a case?

Thanks!

**Comment by jamesaoverton** [comment]
The OWL to OBO conversion is actually being done by OWLAPI https://github.com/owlcs/owlapi/tree/version5/oboformat/src/main/java/org/obolibrary

Unfortunately I don't know enough about OBO format to help. @cmungall is the expert.

**Comment by cmungall** [comment]
Dupe with #64
