### ISSUE TITLE
Merge --inputs fails

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#257]
Works perfect:
robot merge --input "/ws/upheno/src/patterns_owl/abnormal.owl" --input "/ws/upheno/src/patterns_owl/abnormalProcess.owl" --output /data/testmerged.owl

Does not work (but should, according to [docs](http://robot.obolibrary.org/merge))
robot merge --inputs "/ws/upheno/src/patterns_owl/*.owl" --output /data/testmerged.owl 

`java.lang.IllegalArgumentException: at least one inputOntology must be specified
	at org.obolibrary.robot.MergeCommand.execute(MergeCommand.java:117)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:219)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:161)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:121)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)`

**Comment by jamesaoverton** [comment]
Are you using ROBOT 1.0.0? The wildcard feature just landed in `master` and has not yet been packaged into a release.

**Comment by matentzn** [comment]
Okay, good to know. I will watch out for the next release then :) I just got confused because the docs refer to the release, and then mention the command is possible. Thanks for the clarification! You can close this.

**Comment by jamesaoverton** [comment]
You're right: the docs should reflect the latest release. We'll sort that out.
