### ISSUE TITLE
JSON conversion failure

### ISSUE THREAD

**Issue by dosumis** [ontodev/robot#260]
I'd like to generate a JSON version of http://purl.obolibrary.org/obo/geno.owl (there doesn't appear to be a release with this conversion).  JSON conversion works fine for the various OBO ontologies I've tried but geno.owl => 

 ~/bin/robot convert --input geno.owl -f json --output geno.json
java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLAnonymousIndividualImpl cannot be cast to org.semanticweb.owlapi.model.OWLLiteral
	at org.geneontology.obographs.owlapi.FromOwl.generateGraph(FromOwl.java:477)
	at org.geneontology.obographs.owlapi.FromOwl.generateGraphDocument(FromOwl.java:110)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:441)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:414)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:130)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:219)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:161)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:121)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
usage: robot [command] [options] <arguments>

Perhaps issue with punning in GENO ?

CC @mbrush

**Comment by rctauber** [comment]
I'm seeing the same issue, but from the stack trace it looks like this is an obographs issue: https://github.com/geneontology/obographs

@cmungall do you have any ideas about what's going on here?

**Comment by cmungall** [comment]
correct bad code in obographs

**Comment by rctauber** [comment]
Migrated to https://github.com/geneontology/obographs/issues/41
