### ISSUE TITLE
UncheckedExecutionException: java.lang.NullPointerException converting to OBO

### ISSUE THREAD

**Issue by kimrutherford** [ontodev/robot#289]
Hi.

We're getting an exception when converting an OWL file to OBO with robot.  We get the same error when exporting from Protégé (https://github.com/PHI-base/PHI-base_ontologies/issues/13#issuecomment-384944157).  The exception doesn't tell us where to look in the OWL file for problems so we're a bit stuck.

We are attempting to convert this OWL file: https://github.com/PHI-base/PHI-base_ontologies/blob/9db31987944144aa321451753a25dcc1f2b6f2c6/phipo.owl

We're about to start from scratch using the starter kit pointed out to us by @cmungall (https://github.com/INCATools/ontology-starter-kit/) so that we more closely follow what other groups do.    Because we're starting over this exception isn't going to hold us up but we'd like to understand it so we avoid it in future.

Our command line was:

    ./bin/robot convert --input phipo.owl --output phipo.obo

And the error is:

```
2018-05-01 02:41:03,190 ERROR org.obolibrary.obo2owl.OWLAPIObo2Owl - error executing obo id to IRI                                                                                            
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException                                                                                                 
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)                                                                                                               
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)                                                                                                                       
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)                                                                                                                 
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)                                                                                                     
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1664)
        at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:1182)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:74)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:637)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:363)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:203)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:477)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:432)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:174)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
Caused by: java.lang.NullPointerException
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1766)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1705)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl$1.load(OWLAPIObo2Owl.java:81)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl$1.load(OWLAPIObo2Owl.java:77)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        ... 21 more

```

Thanks!

CC: @ValWood @jseager7 @CuzickA

**Comment by dosumis** [comment]
>  error executing obo id to IRI 

As this is OWL to OBO I suspect this is down to a conflict between the obo_id annotation in OWL and the IRI of the OWL entity being converted.  This is a a bug/misfeature of the OBO2OWL conversion code now built into the OWL API.  It's a big problem for Protege too.  If I'm right, then the best ROBOT can do is provide a stack trace that identifies the affected term.  Longer term - the OBO2OWL converter should probably drop support for obo_id Annotation axioms.  Not sure what these are for anyway.

**Comment by kimrutherford** [comment]
Thanks for the explanation David.

> If I'm right, then the best ROBOT can do is provide a stack trace that identifies the affected term.

Yes, that would be helpful.

**Comment by jamesaoverton** [comment]
We've started hiding stack traces by default, but you should still be able to see them using the `-vvv` option. We'll make that more obvious.

**Comment by cmungall** [comment]
in this case, the stack traces are not helpful, this has to be fixed in my obowriter code which is now part of the owlapi.

Not sure what is happening, but removing the imports fixes it. Perhaps some odd interaction to do with the properties in the pato import? 

Some tips for @kimrutherford 

 1. the OWL contains non obolibrary PURLs, you're going to need to do some initial processing before converting. Also non-standard object properties
 2. the imports bring in massive files which will be a pain to work with in general. Current convention is to make an import module but this may be dropped altogether

**Comment by rctauber** [comment]
Based on https://github.com/PHI-base/phipo/issues/13, it looks like this has been fixed for phipo (by adding `--check false`). That said, trying to convert the file without linked above to OBO `--check false` still results in the same error (with a slightly different stack trace):
```
java.lang.NullPointerException
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1739)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1679)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1643)
        ...
```
It would be great to be able to identify the term that's causing this error, but the exception makes that impossible. Should this issue be migrated to the OWLAPI repo?

**Comment by cmungall** [comment]
If someone gives me a the file immediately prior to the command that causes the stacktrace I can at least help provide a more informative owlapi ticket,

**Comment by rctauber** [comment]
I tested it with this file: https://raw.githubusercontent.com/PHI-base/phipo/master/phipo.owl

Converting to OBO results in a partially-written file:
```
[Term]
id: PATO:0002303 ! decreased object quality
is_a: PATO:0001241 ! physical object quality
i
```
Where `i` is the last line, which should read: `is_a: PATO:0002301 ! decreased quality`.

**Comment by cmungall** [comment]
Thanks! This helped me write: https://github.com/owlcs/owlapi/issues/830

We should never have truncated obo in any pipeline if we use the `-o $@.tmp && mv $@.tmp $@` idiom.

@kimrutherford there are a few oddities in the OWL that cause problems in translation

```
    <!-- http://www.geneontology.org/formats/oboInOwl#Subset -->

    <rdf:Description rdf:about="http://www.geneontology.org/formats/oboInOwl#Subset">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000102"/>
    </rdf:Description>
    


    <!-- http://www.w3.org/2002/07/owl#Nothing -->

    <rdf:Description rdf:about="http://www.w3.org/2002/07/owl#Nothing">
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Nothing"/>
    </rdf:Description>
 ```

and also use of hash IRIs for object properties, Nico can advise on correct object property yo use

```
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/pato#towards"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/CHEBI_28909"/>
            </owl:Restriction>
        </rdfs:subClassOf>

```

**Comment by kimrutherford** [comment]
Thanks for looking into this Chris.

> there are a few oddities in the OWL that cause problems in translation

I'll talk to @CuzickA and @jseager7 about the problems.

**Comment by matentzn** [comment]
I am getting nullpointer exceptions like that when trying to deal with OMRSE; but they don't seem to be easily fixable, the stack trace does not reveal much.

**Comment by matentzn** [comment]
Found the reason why OMRSE fails: OBO format writer cant deal with inverse property in class expression!

**Comment by jseager7** [comment]
Sorry about the extremely late reply to this issue. In terms of the oddities in the PHIPO OWL file, it seems the `owl:Nothing subClassOf owl:Nothing` assertion is gone from the ontology now.

- - -

The `oboInOwl#Subset subClassOf IAO_0000102` assertion in still in the latest version of the ontology, now with an `owl:equivalentClass` assertion as well. I'm not sure where these assertions are coming from, since I can't find them in the upstream oboInOwl ontology.

```xml
    <!-- http://www.geneontology.org/formats/oboInOwl#Subset -->

    <owl:Class rdf:about="http://www.geneontology.org/formats/oboInOwl#Subset">
        <owl:equivalentClass>
            <owl:Class>
                <owl:oneOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000224"/>
                </owl:oneOf>
            </owl:Class>
        </owl:equivalentClass>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000102"/>
    </owl:Class>
```
- - -

 I can't find anything in the latest version of the ontology that matches this property:
```xml
<owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/pato#towards"/>
```
Most of our `onProperty` properties have IRIs that end in OBO ID form, like the following:

http://purl.obolibrary.org/obo/BFO_0000050
http://purl.obolibrary.org/obo/RO_0000052

The hash IRIs are all from the ChEBI ontology and PATO, for example:

http://purl.obolibrary.org/obo/chebi#has_functional_parent
http://purl.obolibrary.org/obo/pato#reciprocal_of

Is there anything that we can even do about this? As far as I can tell it seems the OBO Library PURL system just can't cope with IRIs with URI fragments; I can't find any corresponding OBO-style IRIs for these object properties. Is this something that needs addressing in the source ontologies?

**Comment by dillerm** [comment]
@matentzn can I ask what you did to get OMRSE to work?

**Comment by dillerm** [comment]
Yes, I'm getting an error when trying to generate derived ontology files with one of the ODK wrapper scripts. I came across this Github issue and your above comments after Googling the stack trace message I got. Would you prefer for me to log an issue with the full stack trace message on the ODK issue tracker and link it to this issue?

**Comment by matentzn** [comment]
Yes, this would be great. The more info the better
