### ISSUE TITLE
ROBOT writes ERROR on stderr if untranslateable axioms are encountered when saving to obo

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#303]
Sample `foo.omn`:

```
Ontology: <http://x.org/>
Prefix: : <http://x.org/>
DataProperty: P
Class: A SubClassOf: P value "1"^^xsd:int
```

Running convert:

```
$ robot convert -i foo.omn -o foo.obo
2018-06-07 15:54:20,733 ERROR org.obolibrary.obo2owl.OWLAPIOwl2Obo - MASKING ERROR «the axiom is not translated : SubClassOf(<http://x.org/A> DataHasValue(<http://x.org/P> "1"^^xsd:int))»
java.lang.Exception
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2316)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2308)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:2097)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:259)
        at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:228)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:57)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1302)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:477)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:432)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:174)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
```

this is confusing, as foo.obo is successfully written (the file looks odd as untranslateable axioms are hidden in the header, but this is according to spec).

in contrast, this succeeds silently as expected:

```
$ owltools foo.omn -o -f obo foo.obo
```

Perhaps owltools is doing something hacky to suppress the fake errors

**Comment by marieALaporte** [comment]
+1

**Comment by dosumis** [comment]
+2

**Comment by rctauber** [comment]
If you include the following in `log4j.properties` the logging is hidden:
```
log4j.logger.org.obolibrary.obo2owl=off
```

The downside is - if there is useful information coming from that package, it will also be hidden...

**Comment by cmungall** [comment]
Looks like this is common practice: https://github.com/search?q=log4j.logger.org.obolibrary.obo2owl&type=Code

I think a safe assumption is that the useful stuff generally comes out in the stracktrace on an ancaught exception when parsing fails

**Comment by msinclair2** [comment]
This is a question for the use of ROBOT core in an independent project.

I am running a program that converts owl to obo in some steps and uses ROBOT's saveOntology method to do so.  I don't get any MASKING ERROR exceptions when I run it from within my IDE (IntelliJ).  However, when I build it out into a .jar and execute the .jar on the command line, I get the MASKING ERRORs and the conversion is not successful.

**Comment by jamesaoverton** [comment]
@msinclair2 That's strange. My first thought is to try using one of the underlying OWLAPI methods, such as `ontology.getOWLOntologyManager().saveOntology(ontology, format, ontologyIRI)`, and see if that makes a difference.

**Comment by rctauber** [comment]
@msinclair2 On the command line, `convert` defaults to applying the OBO document structure rules. You can ignore this with `--check false`.

**Comment by msinclair2** [comment]
It appears to be related to how I built my jar, or how my IDE built it, as I rebuilt it and I no longer get the error messages. So, probably not an issue with ROBOT or OWLAPI. (I did remember to always set checkOBO to false).

I’ll try to be less trigger happy in the future 😊.

**Comment by jamesaoverton** [comment]
@msinclair2 No problem. Glad it's working now.
