### ISSUE TITLE
Running robot with no parameters should return the help?

### ISSUE THREAD

**Issue by bjonnh** [ontodev/robot#332]
Running robot with no parameters I get:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 4
	at java.lang.String.substring(String.java:1963)
	at org.obolibrary.robot.ExceptionHelper.getExceptionID(ExceptionHelper.java:50)
	at org.obolibrary.robot.ExceptionHelper.handleException(ExceptionHelper.java:26)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:141)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)

Maybe that would be more useful if it returned the help?

**Comment by jamesaoverton** [comment]
Thanks, that's definitely a bug!

Fortunately the exception points right to the problem. We'll get that fixed.

**Comment by bjonnh** [comment]
Please see #333 for a proposition of fix.

**Comment by rctauber** [comment]
Resolved by #333
