### ISSUE TITLE
ROBOT's OWL to OBO conversion fails:  multiple comment tags not allowed

### ISSUE THREAD

**Issue by msinclair2** [ontodev/robot#338]
I'm getting the following exception when trying to use ROBOT to convert an OWL to OBO:

`Exception in thread "main" java.io.IOException: org.semanticweb.owlapi.model.OWLOntologyStorageException: org.obolibrary.oboformat.model.FrameStructureException: multiple comment tags not allowed. in frame:Frame(MSO:0000340 id( MSO:0000340)is_a( MSO:3100248)property_value( IAO:0000118 chromosome xsd:string)def( The central nucleic acid of a chromosome that controls its own replication through the interaction of specific proteins at one or more origins of replication.[SO:ma ])comment( This term is mapped to MGED. Do not obsolete without consulting MGED ontology.)comment( This class and its subclasses are intentionally referred to as chromosomal nucleic acids for their primary labels and not more simply as chromosomes so as to distinguish them from chromosomes as represented in the Gene Ontology (GO:0005694 and its subclasses): While the SO/MSO classes specifically refer to the primary nucleic acids constituting chromosomes, the GO classes also include associated molecules, e.g., histones.)subset( SOFA)name( chromosomal nucleic acid))`

The class in question has two rdfs:comment annotations.  Shouldn't this definitely be allowed?

**Comment by rctauber** [comment]
Hi @msinclair2 - if you run the convert with the `--check false` option, it should allow multiple `rdfs:comment` annotations. Let me know if this works!

**Comment by msinclair2** [comment]
Thanks, that gets me past that error.  Although the OBO Format specification says that multiple comments in OWL should just be concatenated with new line characters when converted to OBO.

However I'm now getting this error, which I've encountered before, and I don't think is ROBOT's problem, but here it is:

```
Exception in thread "main" java.lang.IllegalArgumentException: URI is not absolute
	at java.io.File.<init>(File.java:416)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:550)
	at com.MSO.java.Main.main(Main.java:75)
```
The ontology definitely has an IRI, but I'm not sure how to make it absolute.

**Comment by jamesaoverton** [comment]
One option is to use the `robot annotate` command to set the ontology IRI to something absolute. http://robot.obolibrary.org/annotate

**Comment by msinclair2** [comment]
@jamesaoverton The confusing thing is that I already have an absolute ontology IRI.

**Comment by jamesaoverton** [comment]
Ok, then ROBOT is getting confused about where you want to save the ontology to. I usually just use a simple file path like `--output somefile.owl`. Can you share the full `robot` command that you're running?

**Comment by msinclair2** [comment]
Sure, I'm using ROBOT core inside my own project, so I'll paste the code below.

```
        OBODocumentFormat oboFormat = new OBODocumentFormat();
        ioHelper.saveOntology(MSO_reasoned, oboFormat, IRI.create("files/MSO_reasoned.obo"), false);
```

**Comment by jamesaoverton** [comment]
Ok. Instead of `IRI.create("files/MSO_reasoned.obo")`, try `IRI.create(File("files/MSO_reasoned.obo"))`

**Comment by msinclair2** [comment]
Let me try passing the location as a File object instead.

**Comment by rctauber** [comment]
Yup! #340

**Comment by msinclair2** [comment]
So the real issue here is that the IRI for the physical location also has to be absolute (i.e. file://....).
