### ISSUE TITLE
Report command has String Index out of range: -1 when running a certain query

### ISSUE THREAD

**Issue by dougli1sqrd** [ontodev/robot#400]
In go-ontology we have a query to detect forward and trailing whitespace in string values. I have adapted it to be used in a profile. 
```
# home: hp/sparql/trailing-whitespace-violation.sparql
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?property ?value
WHERE 
{
  ?entity ?property ?value .

  FILTER( regex(STR(?value), "^ ") || regex(STR(?value), " $")  )
  FILTER( ?property != owl:annotatedTarget )
}

```
If I add `WARN	file:../sparql/trailing-whitespace-violation.sparql` to my profile.txt, I get the following error:
```
2018-11-07 16:23:16,087 INFO  org.obolibrary.robot.QueryOperation - Named graph added: http://purl.obolibrary.org/obo/go.owl
2018-11-07 16:23:16,087 DEBUG org.obolibrary.robot.ExceptionHelper - Missing exception ID: String index out of range: -1
String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1927)
	at org.obolibrary.robot.ReportOperation.report(ReportOperation.java:193)
	at org.obolibrary.robot.ReportCommand.execute(ReportCommand.java:120)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:54)
```

For comparison, if I introduce a space and I run the same query with the `query` command, I get: 
```
edouglass@Erics-MBP-2:~/lbl/geneontology/go-ontology/src/ontology[master *?]$ robot query --input go-fake.obo --query ../sparql/trailing-whitespace-violation.sparql out && cat out
entity,property,value
http://purl.obolibrary.org/obo/GO_0000006,http://purl.obolibrary.org/obo/IAO_0000115,"Enables the transfer of zinc ions (Zn2+) from one side of a membrane to the other, probably powered by proton motive force. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations. "
```

I haven't looked into why this could be the case, but if you want I can dig around?

**Comment by rctauber** [comment]
Thanks for finding this!

I just looked into it and the problem is that the command expects a `PREFIX` instead of `prefix` to start the query string at (removing the comments at the beginning). If I change the query to start with the following, it works fine:
```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
```

This isn't the best way to do this - it should just look for the first line that doesn't start with a `#`. I'll make a fix for it and push it to #394.

As a side note, there is an existing report query that checks for leading and trailing whitespace: http://robot.obolibrary.org/report_queries/annotation_whitespace

**Comment by dougli1sqrd** [comment]
Ah good to know! I'll just remove the go-ontology whitespace check and it should be good then. Thanks!

**Comment by balhoff** [comment]
@dougli1sqrd it's possible that [STRSTARTS](https://www.w3.org/TR/sparql11-query/#func-strstarts) and [STRENDS](https://www.w3.org/TR/sparql11-query/#func-strends) could be much faster than regex for this.

**Comment by balhoff** [comment]
Oh I see @rctauber has already got that in hers.

**Comment by rctauber** [comment]
No worries, this is a good find. The report queries that are included in the JAR have to be processed by an Input Stream from the jar, so they aren't newline-separated. So to remove headers, it was looking for the first occurrence of `PREFIX` to make a substring.

Anyway, I changed the processing a little bit and it should work fine with both the JAR-included queries and user queries, even if they don't include `PREFIX`.
