### ISSUE TITLE
Running remove appears to be consuming (too) much memory (CLO)

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#529]
Running:

```
robot remove -I http://purl.obolibrary.org/obo/clo.owl --term rdfs:label --select complement --select annotation-properties  -o test.owl
```
(Command to remove all annotations except for labels from the ontology).

In Robot 1.4.1 with 8GB RAM (ROBOT java memory) results in an OutOfMemoryError exception; this seems excessive, is there perhaps a bug hidden here?

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:840)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at com.google.common.collect.Iterables.addAll(Iterables.java:352)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.asSet(OWLImmutableOntologyImpl.java:805)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getAxioms(OWLImmutableOntologyImpl.java:1325)
	at uk.ac.manchester.cs.owl.owlapi.OWLAxiomIndexImpl.getSubClassAxiomsForSubClass(OWLAxiomIndexImpl.java:136)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getSubClassAxiomsForSubClass(ConcurrentOWLOntologyImpl.java:1768)
	at org.semanticweb.owlapi.search.EntitySearcher.getSuperClasses(EntitySearcher.java:805)
	at org.obolibrary.robot.RelatedObjectsHelper.getSuperClasses(RelatedObjectsHelper.java:1014)
	at org.obolibrary.robot.RelatedObjectsHelper.spanGapsHelper(RelatedObjectsHelper.java:1403)
```

**Comment by matentzn** [comment]
(actually running this command in isolation takes excessively long, I first encountered the error when running from within docker container)

**Comment by matentzn** [comment]
It seems to relate to the same issue:

when running:
```
robot --catalog catalog-v001.xml merge --input cl-edit.owl  -i ../patterns/definitions.owl \
	reason --reasoner ELK \
	relax \
	remove --axioms equivalent \
	remove --term-file keeprelations.txt --select complement --select object-properties --trim true \
	relax \
	filter --term-file simple_seed.txt --select "annotations ontology anonymous object-properties self" --trim true --signature true \
	reduce -r ELK \
	annotate --ontology-iri http://purl.obolibrary.org/obo/cl/cl-basic.owl --version-iri http://purl.obolibrary.org/obo/cl/releases/2019-07-07/cl-basic.owl --output cl-basic.owl.tmp.owl
```

I get:
```
Exception in thread "main" java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at com.google.common.collect.Iterables.addAll(Iterables.java:352)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.asSet(OWLImmutableOntologyImpl.java:805)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getAxioms(OWLImmutableOntologyImpl.java:1325)
	at uk.ac.manchester.cs.owl.owlapi.OWLAxiomIndexImpl.getSubClassAxiomsForSubClass(OWLAxiomIndexImpl.java:136)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getSubClassAxiomsForSubClass(ConcurrentOWLOntologyImpl.java:1768)
	at org.semanticweb.owlapi.search.EntitySearcher.getSuperClasses(EntitySearcher.java:805)
	at org.obolibrary.robot.RelatedObjectsHelper.getSuperClasses(RelatedObjectsHelper.java:1014)
	at org.obolibrary.robot.RelatedObjectsHelper.spanGapsHelper(RelatedObjectsHelper.java:1
```

**Comment by rctauber** [comment]
Thanks for pointing this out. I'll take a look at what's going on. 

If you're just removing annotations, `--preserve-structure false` will help speed things up.

**Comment by rctauber** [comment]
I suspect that the second exception has to do with removing the equivalent axioms, just like #527

**Comment by matentzn** [comment]
I think I need --preserve structure true :/ :P Thanks for looking into this.

**Comment by beckyjackson** [comment]
The second exception should have been resolved by #547 
Is this OK to close?
