### ISSUE TITLE
'null' on IncoherentTBoxException

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#582]
On running `reason`:
```
2019-10-29 08:49:45,819 ERROR org.obolibrary.robot.ReasonerHelper - There are 1 unsatisfiable classes in the ontology.
2019-10-29 08:49:45,819 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/OBI_0000234
null
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

Stack trace shows: 
```
2019-10-30 07:40:00,691 DEBUG org.obolibrary.robot.ExceptionHelper - {} missing exception message.
org.obolibrary.robot.exceptions.IncoherentTBoxException
	at org.obolibrary.robot.ReasonerHelper.validate(ReasonerHelper.java:113)
	at org.obolibrary.robot.ReasonerHelper.validate(ReasonerHelper.java:58)
	at org.obolibrary.robot.ReasonOperation.reason(ReasonOperation.java:543)
	at org.obolibrary.robot.ReasonOperation.reason(ReasonOperation.java:102)
	at org.obolibrary.robot.ReasonCommand.execute(ReasonCommand.java:176)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:56)
null
```

**Comment by beckyjackson** [comment]
Resolved by #583
