### ISSUE TITLE
Extracting terms from schema.org fails with: java.lang.NullPointerException: Ontology IRI cannot be null

### ISSUE THREAD

**Issue by bjonnh** [ontodev/robot#681]
MNWE:

robot extract --method STAR --input imports/schema.org/source.rdf --term-file imports/schema.org/terms.txt

where source.rdf is : http://schema.org/version/latest/schema.rdf
terms.txt contains : http://schema.org/about 

Robot fails with: Ontology IRI cannot be null

Stack trace:
java.lang.NullPointerException: Ontology IRI cannot be null
        at org.semanticweb.owlapi.util.OWLAPIPreconditions.checkNotNull(OWLAPIPreconditions.java:98)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.contains(OWLOntologyManagerImpl.java:316)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.createOntology(OWLOntologyManagerImpl.java:997)
        at org.obolibrary.robot.ExtractOperation.extract(ExtractOperation.java:162)
        at org.obolibrary.robot.ExtractCommand.slmeExtract(ExtractCommand.java:347)
        at org.obolibrary.robot.ExtractCommand.execute(ExtractCommand.java:192)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:58)

**Comment by jamesaoverton** [comment]
Weird. That stack trace points to [OWLAPI](https://github.com/owlcs/owlapi) being the cause.

As a workaround, you can easily add an Ontology IRI with [`robot annotate`](http://robot.obolibrary.org/annotate).

Can anybody suggest a better solution?

**Comment by balhoff** [comment]
The input file is RDF, but doesn't look like an OWL ontology. On the other hand, Protege seems to be able to load it.

**Comment by bjonnh** [comment]
My workaround for now is to add --output-iri http://schema.org
