### ISSUE TITLE
Robot raise a ONTOLOGY STORAGE ERROR when template gets an rdfxml error

### ISSUE THREAD

**Issue by bjonnh** [ontodev/robot#688]
The error is a bit misleading, as I was just missing a prefix
And it is solved in that case by adding the ero prefix.

(of course Robot has write access to /tmp (it works with merge and extract))

java.io.IOException: errors#ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/tmp/tables.owl
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1406)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:716)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:669)
        at org.obolibrary.robot.TemplateCommand.execute(TemplateCommand.java:190)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:58)
Caused by: org.semanticweb.owlapi.model.OWLOntologyStorageException: ero:0000480
ero:0000041
        at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLStorer.storeOntology(RDFXMLStorer.java:57)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1478)
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1398)
        ... 7 more
Caused by: org.semanticweb.owlapi.rdf.rdfxml.renderer.IllegalElementNameException: Illegal Element Name (Element Is Not A QName): ero:0000480
ero:0000041

**Comment by beckyjackson** [comment]
Hi @bjonnh - thanks for bringing this up! `ONTOLOGY STORAGE ERROR` is a bit misleading here, I think it would be more helpful to look at the `IllegalElementNameException` and provide a message related to that.

Could you provide me with the command and input files you were using when you got this message? Thanks!

**Comment by bjonnh** [comment]
# Minimal non-working example

save that as a csv (/tmp/test.csv):

```
ID,type,hasURL
ID,TYPE,A ero:0000480
nav:0000001,nav:Tool,http://www.test.com/

```
*$* robot template --template /tmp/test.csv --output /tmp/test.owl
**will fail with:**
```
ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/tmp/test.owl
For details see: http://robot.obolibrary.org/errors#ontology-storage-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.


```
*$* robot template --template /tmp/test.csv --prefix "ero: http://a" --output /tmp/test.owl
**will finish successfully.**

**Comment by jamesaoverton** [comment]
@bjonnh If you have a minute, can you please check that #688 fixes this issue, using the JAR here: https://build.obolibrary.io/job/ontodev/job/robot/job/688-fix/lastSuccessfulBuild/artifact/bin/robot.jar

**Comment by bjonnh** [comment]
It does solve it. Thanks for the quick fix.
