### ISSUE TITLE
Add examples for use of MIREOT extraction method

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#73]
MIREOT works in a slightly different way than the SLME methods, taking upper and lower bounds. When running `robot extract -h` it's not clear which options apply where

**Comment by jmcamza** [comment]
I don`t know how to use this method, I get this error when I try to use the extract command:

jmcamza$ robot extract --input chebi.owl --method MIREOT --term-file molecular_entity_uniq_CHEBI.txt --output chebi_molecular_entity_MIREOT_2.owl
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.obolibrary.robot.MergeOperation.merge(MergeOperation.java:50)
	at org.obolibrary.robot.ExtractCommand.execute(ExtractCommand.java:173)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:50)

Can anyone help me with this?

**Comment by jamesaoverton** [comment]
MIREOT is different from the other methods because it requires you to specify "upper" and "lower" limits for the extraction. I added an example here:

https://github.com/ontodev/robot/blob/master/examples/README.md#extracting
