### ISSUE TITLE
ROBOT report has redundant \t (tab) in all all rows except header row.

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#737]
Version: ROBOT 1.7.0

```
robot report -I https://raw.githubusercontent.com/ontodev/robot/master/robot-core/src/test/resources/map_properties_up_test.owl --fail-on none --print 5 -o obo-report.tsv
cat obo-report.tsv | grep -E '.*(\t.*){4}' | wc -l # 61
cat obo-report.tsv | grep -E '.*(\t.*){5}' | wc -l # 60
```

On closer inspection, you can see that all lines apart from the header row have redundant `\t` characters in the end.

This confuses some tools (python libraries), while others, such as Excel or Numbers, appear unaffected.

![image](https://user-images.githubusercontent.com/7070631/93239574-e2b7f980-f77a-11ea-9cd0-223bcad93e1a.png)

**Comment by beckyjackson** [comment]
I see this happening when I use v1.7.0 but it appears to be fixed in our unreleased version. Could you try with [this JAR](https://build.obolibrary.io/job/ontodev/job/robot/job/master/lastSuccessfulBuild/artifact/bin/robot.jar) and let me know if it works for you?

1.7.0:
![image](https://user-images.githubusercontent.com/16750150/93811819-ba1e7c80-fc1e-11ea-96ef-10a79dd03f32.png)

Unreleased:
![image](https://user-images.githubusercontent.com/16750150/93811793-ae32ba80-fc1e-11ea-8219-b9043384e459.png)

We may need to address the fact that the ontology IRI is being turned into a CURIE, though...

**Comment by matentzn** [comment]
Thanks a _lot_ for looking into this! Hmm. Unfortunately I get this error, which seems unrelated:

```
robot report -i mondo.owl --fail-on none --print 5 -o test.tsv
2020-09-21 20:50:39,597 ERROR org.obolibrary.robot.ReportOperation - Could not complete query 'lowercase_definition' - report may be incomplete.
Cause:
iri cannot be null
report#MISSING ENTITY BINDING query 'lowercase_definition' must include an '?entity'
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

Never seen that before!

**Comment by beckyjackson** [comment]
I think the key to that error is "iri cannot be null". Could you send me the full stack trace?

**Comment by matentzn** [comment]
Thats all I think:

```
2020-09-21 21:04:25,235 ERROR org.obolibrary.robot.ReportOperation - Could not complete query 'lowercase_definition' - report may be incomplete.
Cause:
iri cannot be null
2020-09-21 21:04:25,236 DEBUG org.obolibrary.robot.ExceptionHelper - Missing exception ID: report#MISSING ENTITY BINDING query 'lowercase_definition' must include an '?entity'
report#MISSING ENTITY BINDING query 'lowercase_definition' must include an '?entity'
java.lang.Exception: report#MISSING ENTITY BINDING query 'lowercase_definition' must include an '?entity'
	at org.obolibrary.robot.ReportOperation.getReport(ReportOperation.java:287)
	at org.obolibrary.robot.ReportOperation.report(ReportOperation.java:233)
	at org.obolibrary.robot.ReportCommand.execute(ReportCommand.java:148)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```

**Comment by matentzn** [comment]
I am pretty sure this was fixed? @beckyjackson
