### ISSUE TITLE
When a ontology parse fails, robot gives a misleading error message

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#83]
Example z.omn:

```
Ontology: x

## foo
Class: foo
 Annotations: rdfs:label "xx"
```

```
obot convert -i z.omn -o z.owl
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
java.lang.IllegalArgumentException: An input ontology must be specified
        at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:352)
        at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:314)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:127)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:50)
```

In fact the error is caused by a failure to parse the omn. Using owltools gives the usual verbose response where every parser is attempted

May have been at the root of some of #56

**Comment by vasiliy-bout** [comment]
I have this problem too. When I try to use `robot` it gives me the same error:
```
$ robot convert --input cellosaurus.obo --format OWL --output cellosaurus.owl 
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
WARN  LINE: 425 accepting bad xref with spaces:<IZSLER:BS CL 93>  LINE:
xref: IZSLER:BS CL 93
WARN  LINE: 759 accepting bad xref with spaces:<TKG:TKG 0614>  LINE:
xref: TKG:TKG 0614

... many WARN messages here ...

WARN  LINE: 224200 accepting bad xref with spaces:<TKG:TKG 0481>  LINE:
xref: TKG:TKG 0481
WARN  LINE: 224309 accepting bad xref with spaces:<IZSLER:BS CL 39>  LINE:
xref: IZSLER:BS CL 39
java.lang.IllegalArgumentException: An input ontology must be specified
	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:352)
	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:314)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:127)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:50)
usage: robot [command] [options] <arguments>
 -h,--help             print usage information
 -noprefixes           do not use default prefixes
 -P,--prefixes <arg>   use prefixes from JSON-LD file
 -p,--prefix <arg>     add a prefix 'foo: http://bar'
 -v,--version          print version information
commands:
 help            print help for command
 annotate        annotate ontology
 convert         convert ontology
 diff            find the differences between two ontologies
 export-prefixes export prefixes to a file
 extract         extract terms from an ontology
 filter          filter ontology axioms
 merge           merge ontologies
 reason          reason ontology
 reduce          reduce ontology
 relax           relax ontology
 template        build an ontology from a template
```

But when I use owltools, it gives me correct error message. It tries all possible parsers, so the output contains many different errors, but since I know that my input file is in OBO format, I can choose the error message from the corresponding OBO parser `OBOFormatOWLAPIParser`:
```
Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@5b04476e
    Stack trace:
LINENO: 224456 - expected newline or end of line but found: ]-T0003.html
LINE: xref: https://www.abmgood.com/Immortalized-Vascular-Endothelial-Cells-[EC-RF24]-T0003.html        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:60)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:197)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935)
        uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:891)
        owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:157)
        owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:144)
        owltools.io.ParserWrapper.parseOBO(ParserWrapper.java:130)
        owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4011)
LINENO: 224456 - expected newline or end of line but found: ]-T0003.html
LINE: xref: https://www.abmgood.com/Immortalized-Vascular-Endothelial-Cells-[EC-RF24]-T0003.html        org.obolibrary.oboformat.parser.OBOFormatParser.error(OBOFormatParser.java:1501)
        org.obolibrary.oboformat.parser.OBOFormatParser.forceParseNlOrEof(OBOFormatParser.java:1339)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseEOL(OBOFormatParser.java:1307)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseTermFrameClauseEOL(OBOFormatParser.java:629)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseTermFrame(OBOFormatParser.java:601)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseEntityFrame(OBOFormatParser.java:566)
        org.obolibrary.oboformat.parser.OBOFormatParser.parseOBODoc(OBOFormatParser.java:381)
        org.obolibrary.oboformat.parser.OBOFormatParser.parse(OBOFormatParser.java:335)
        org.obolibrary.oboformat.parser.OBOFormatParser.parse(OBOFormatParser.java:281)
        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:76)
```

This means that the `robot` gives completely incorrect error message. And it seems to me that this incorrect message occurs for any kind of errors...

**Comment by jamesaoverton** [comment]
Thanks for the report. I agree that this is a misleading error message, and has to be improved.
