### ISSUE TITLE
ROBOT report: misleading "MISSING ENTITY BINDING" for language-tagged string in ?property variable

### ISSUE THREAD

**Issue by jclerman** [ontodev/robot#900]
I just spent some extra time debugging a `report` query due to a misleading error message.  Admittedly my use-case may be an abuse of the `report` functionality, but nonetheless: 

Turns out that if a `report` query happens to return a language-tagged string as the value for `?property`, ROBOT report fails with this stack-trace:

```
java.lang.Exception: report#MISSING ENTITY BINDING query 'file:./tests/content/sparql/missing-materializations-nontransitive.rq' must include an '?entity'
	at org.obolibrary.robot.ReportOperation.getReport(ReportOperation.java:287)
	at org.obolibrary.robot.ReportOperation.report(ReportOperation.java:233)
	at org.obolibrary.robot.ReportCommand.execute(ReportCommand.java:148)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```

Despite the error message, the problem has nothing to do with the `?entity` variable (which is indeed bound by the query, and which is indeed an IRI in all cases).

It'd be nice to update the error-detection logic to produce a more-correct error message.  I assume the issue here is that there is no defined serialization for language-tagged strings, at least not for the *.TSV format that I'm using for my report output; assuming that's true, the error message should ideally indicate something to that effect, and in particular should blame the `?property` binding rather than the `?entity` binding.

**Comment by matentzn** [comment]
Hey @jclerman 

would you be able to provide us with a reproducible example for this? Thank you! :)
