### ISSUE TITLE
Handle errors properly when saving to OboGraphJsonDocumentFormat

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#906]
I think we're missing error handling code for this block:

https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java#L1709

**Comment by beckyjackson** [comment]
I'm not entirely sure what the error message should be, or what we can suggest to fix it? Do you have any ideas?

**Comment by matentzn** [comment]
Test case:

```
robot -vvv convert -I https://raw.githubusercontent.com/edamontology/edamontology/main/releases/EDAM.owl -f json -o edam.json
```

Results in annoying error:

```
2021-08-31 17:50:32,510 DEBUG org.obolibrary.robot.ExceptionHelper - {} missing exception message.
java.lang.NullPointerException
	at org.geneontology.obographs.owlapi.FromOwl.generateGraph(FromOwl.java:409)
	at org.geneontology.obographs.owlapi.FromOwl.generateGraphDocument(FromOwl.java:63)
	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1684)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
	at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
null
java.lang.NullPointerException
	at org.geneontology.obographs.owlapi.FromOwl.generateGraph(FromOwl.java:409)
	at org.geneontology.obographs.owlapi.FromOwl.generateGraphDocument(FromOwl.java:63)
	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1684)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
	at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```

I guess it could fail more gracefully?

**Comment by jamesaoverton** [comment]
Thanks @matentzn. We can't do too much here, but we can fix the "{} missing exception message." and maybe point to the https://github.com/geneontology/obographs repo.
