### ISSUE TITLE
Test ROBOT with GraalVM

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#915]
[GraalVM](https://www.graalvm.org/) includes a tool called [`native-image`](https://www.graalvm.org/reference-manual/native-image/) that can convert a Java JAR file to a platform-native binary that can be executed without needing a JVM installed. This could simplify the ROBOT installation instructions to just: download the binary for your platform. However there may be a performance hit.

**Comment by beckyjackson** [comment]
This is cool! I was able to build an image and it runs fine, but I haven't tested performance against the JAR yet. That said, the image I built is not a standalone image and can only be run from within the ROBOT directory. We can build a standalone image using the `--no-fallback` option, but when I try to run this image, it fails:
```
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError
	at org.apache.log4j.Category.class$(Category.java:118)
	at org.apache.log4j.Category.<clinit>(Category.java:118)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at java.lang.Class.ensureInitialized(DynamicHub.java:552)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:82)
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.obolibrary.robot.CommandManager.<clinit>(CommandManager.java:19)
	at org.obolibrary.robot.CommandLineInterface.initManager(CommandLineInterface.java:21)
	at org.obolibrary.robot.CommandLineInterface.<clinit>(CommandLineInterface.java:13)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Category
	at java.lang.Class.forName(DynamicHub.java:1433)
	at java.lang.Class.forName(DynamicHub.java:1408)
	... 16 more
```

Could somebody else try building an image using `--no-fallback` to see if this is something weird on my system, or if it's a problem with `log4j`?

**Comment by beckyjackson** [comment]
Ah, I should have checked that first. Upgrading slf4j-log4j doesn't resolve the problem. It seems like it has something to do with [this comment](https://github.com/oracle/graal/issues/2008#issuecomment-569530312).

**Comment by jamesaoverton** [comment]
I guess it's worth a try. I think we used slf4j because OWLAPI does: https://github.com/owlcs/owlapi/blob/version5/pom.xml#L115
