### ISSUE TITLE
report no longer supporting custom sparql queries in profile in 1.8.2

### ISSUE THREAD

**Issue by Clare72** [ontodev/robot#943]
I was running two custom sparql queries using the report function with this [qc-profile.txt](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/v2021-10-14/src/ontology/qc-profile.txt) file. This works fine with robot 1.8.1, but is no longer working with 1.8.2.

running this command with 1.8.2:
`robot -vvv --catalog catalog-v001.xml report -i fbbt.obo --profile qc-profile.txt --fail-on ERROR --print 5 -o obo_qc_fbbt.obo.txt`

ends with a NullPointerException:
```
2021-12-07 13:03:12,571 DEBUG org.obolibrary.robot.ExceptionHelper - {} missing exception message.
java.lang.NullPointerException
	at org.obolibrary.robot.checks.Report.addReportQuery(Report.java:209)
	at org.obolibrary.robot.ReportOperation.getReport(ReportOperation.java:293)
	at org.obolibrary.robot.ReportOperation.report(ReportOperation.java:234)
	at org.obolibrary.robot.ReportCommand.execute(ReportCommand.java:153)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
null
java.lang.NullPointerException
	at org.obolibrary.robot.checks.Report.addReportQuery(Report.java:209)
	at org.obolibrary.robot.ReportOperation.getReport(ReportOperation.java:293)
	at org.obolibrary.robot.ReportOperation.report(ReportOperation.java:234)
	at org.obolibrary.robot.ReportCommand.execute(ReportCommand.java:153)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```

[edit] Forgot to say in original version of post - this works fine in 1.8.2 without the two custom queries, i.e. if these lines are removed:
`ERROR	file:../sparql/duplicate_label_fbbt.sparql`
`ERROR	file:../sparql/duplicate_symbol.sparql`

**Comment by matentzn** [comment]
Yes, this is a bug - I can reproduce it. This needs a hotfix and a new integration test..

**Comment by matentzn** [comment]
BTW @Clare72 since you seem to use ODK, you can for now move those to checks to ROBOT verify simply by

- removing them from profile.txt
- adding them to ROBOT verify like that: https://github.com/pato-ontology/pato/blob/master/src/ontology/pato-odk.yaml#L63

**Comment by matentzn** [comment]
alternatively you can just use ODK 1.2.30 until this is fixed.

**Comment by gouttegd** [comment]
The problem seems to be that in `org.obolibrary.robot.ReportOperation`, there is a discrepancy between what the `getProfile(String)` method is doing and what the `getReportQueries(Map<String, String>)` is expecting.

`getProfile(String)` does the following:

```java
while ((line = br.readLine()) != null) {
        String[] split = line.trim().split("\t");
        /* ... */
        String rule = split[1];
        profile.put(rule, level);
      }
```

that is, it sets the key to the entire value found in the profile (e.g., `file:path/to/rule.sparql`).

But then `getReportQueries(Map<String, String>)` does the following:

```java
for (Map.Entry<String, String> qs : userQueryStrings.entrySet()) {
      String rulePath = qs.getKey();
      String ruleName = rulePath.substring(rulePath.lastIndexOf("/") + 1, rulePath.lastIndexOf("."));
      ReportQuery rq = new ReportQuery(ruleName, qs.getValue(), profile.get(ruleName));
      reportQueries.add(rq);
    }
```

that is, it looks up the level associated with the rule by searching for a rule name containing only the basename.

**Comment by Clare72** [comment]
@matentzn, I am just removing those two checks from the profile for now (it is very unlikely that the problems they catch will happen) and will put them back when this is issue is fixed (and fix gets into odk).

**Comment by jamesaoverton** [comment]
Thanks everyone for finding and fixing this problem. It should be fixed on `master` now. If anyone has time to double-check that, I'd appreciate it.

I will make a 1.8.3 release with this fix. But I want to wait until tomorrow -- I didn't sleep well, so I've been making stupid mistakes all morning, and I don't want to mess up a release.

**Comment by gouttegd** [comment]
Works here on FBbt (with the two custom tests added back) from the tip of the master branch. :+1:
