### ISSUE TITLE
null error on saving OBO file

### ISSUE THREAD

**Issue by reality** [ontodev/robot#959]
I get an error running the following (it is the OBO make component in ODK for RBO):

```bash
robot --catalog catalog-v001.xml convert --input rbo.owl --check false -f obo -o rbo.obo.tmp.obo
```

The error is the string 'null' and a non-normal exit. 

Adding -vvv I get:

```bash
2022-01-13 12:33:06,995 DEBUG org.obolibrary.robot.IOHelper - Saving ontology as OBO Format with to IRI file:/home/luke/RBO/src/ontology/rbo.obo.tmp.obo
2022-01-13 12:33:07,453 DEBUG org.obolibrary.robot.ExceptionHelper - {} missing exception message.
java.lang.NullPointerException
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:619)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:171)
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1700)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:59)
null
java.lang.NullPointerException
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:619)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:171)
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1700)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:59)
```

I suppose it has come across some input it doesn't like/cannot convert? The rbo.obo.tmp.obo file is created, and gets about 1/4th of the way through what its final size should be. It did work previously so some new component introduced via imports in ODK have probably caused the issue... I suppose the primary issue is that it is not outputting info on where the issue is in the input.

repeatability: every time
version: 1.9.0-SNAPSHOT

If you would like to reproduce yourself, ```make rbo.obo``` run on this commit https://github.com/Radiobiology-Informatics-Consortium/RBO/commit/49b617f85b429691bdf4d3cebe101f3840f5a01e should cause it to occur. You can also see the error in travis: https://app.travis-ci.com/github/Radiobiology-Informatics-Consortium/RBO/builds/244752896 

Thanks a lot!

**Comment by reality** [comment]
So I can run --check true to get (what I assume, will confirm later) is the cause of the error:

```
OBO STRUCTURE ERROR Ontology does not conform to OBO structure rules:
multiple def tags not allowed. in frame:Frame(GO:0050896 id( GO:0050896)xref( GO:0050896)def( 
Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulus. The process begins with detection of the stimulus and ends with a change in state or activity or the cell or organism.
)property_value( IAO:0000117 Helen Parkinson xsd:string)subset( gocheck_do_not_manually_annotate)comment( 
Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select a child term or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC.
)subset( goslim_mouse)subset( goslim_agr)property_value( IAO:0000412 http://purl.obolibrary.org/obo/go.owl)name( response to stimulus)def( Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulus. The process begins with detection of the stimulus and ends with a change in state or activity or the cell or organism.[GOC:ai GOC:bf ])namespace( biological_process)subset( goslim_flybase_ribbon)subset( gosubset_prok)synonym( response to treatment EXACT)synonym( physiological response to stimulus EXACT)subset( goslim_pir)comment( Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select a child term or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC.)xref( SNOMEDCT:248237001)alt_id( GO:0051869)is_a( GO:0008150))
For details see: http://robot.obolibrary.org/errors#obo-structure-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

So perhaps all this needs is an exception message with something like "Failed to parse, please use --check true to identify cause```?

**Comment by reality** [comment]
Also, any tips on what to do about the error itself would be appreciated too... Is it not possible to convert while ignoring problematic input. Is that what --check false is supposed to do? Is the issue different from this OBO syntax conformation error?

**Comment by jamesaoverton** [comment]
@reality I'm not an OBO-format expert, but there are parts of RDF and OWL that OBO-format just can't express. I'm not aware of any tools that will automatically filter those parts out. For my projects we tend to manually delete problem parts before converting to OBO-format. If someone has a better way of doing this, please let us know. Here's an example:

https://github.com/obi-ontology/obi/blob/master/Makefile#L200

@beckyjackson We should never see `DEBUG org.obolibrary.robot.ExceptionHelper - {} missing exception message.` right? I think @reality is right that we should have a message and point to docs at http://robot.obolibrary.org/errors#obo-structure-error

**Comment by cmungall** [comment]
I deeply apologize for the opaqueness of this error/stack trace. Really the fix needs to happen in the obo writer which lives in the owlapi repo - if you make an issue there there is a chance someone may be able to work on it.

This bug seems to be usually caused by an issue with ObjectProperties

**Comment by DanBerrios** [comment]
@beckyjackson @matentzn @cmungall  @reality We still see this same stack trace/error even if we use don't check structure, i.e.,:

robot --catalog catalog-v001.xml convert --input rbo.owl --check false -f obo  -o rbo.obo.tmp.obo -vvv

`DEBUG Saving ontology as OBO Format with to IRI file:/C:/Users/Dan/Documents/GitHub/RBO/src/ontology/rbo.obo.tmp.obo
DEBUG {} missing exception message.
java.lang.NullPointerException: null
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:619)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1478)
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1730)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:846)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:667)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
null`

**Comment by beckyjackson** [comment]
Hi @DanBerrios - what version of ROBOT are you using? The last release we made was v1.8.3 back in December, so this fix is not included in the latest version. If you build from `master` or use [this JAR](https://build.obolibrary.io/job/ontodev/job/robot/job/master/lastSuccessfulBuild/artifact/bin/robot.jar), this is what I see:
```
$ robot --catalog catalog-v001.xml convert --input rbo.owl --check false -f obo -o rbo.obo.tmp.obo
OBO STRUCTURE ERROR ontology cannot be saved in OBO format. Please use '--check true' to see cause.
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

We are looking to make a new release soon.
