### ISSUE TITLE
annotate command axiom-annotation parameter

### ISSUE THREAD

**Issue by hkir-dev** [ontodev/robot#974]
Robot annotate `--axiom-annotation` parameter is always giving the below error:
```
java.lang.UnsupportedOperationException: errors#AXIOM TYPE ERROR cannot annotate axioms of type: class uk.ac.manchester.cs.owl.owlapi.OWLAnnotationAssertionAxiomImpl
	at org.obolibrary.robot.OntologyHelper.addAxiomAnnotation(OntologyHelper.java:95)
	at org.obolibrary.robot.OntologyHelper.addAxiomAnnotation(OntologyHelper.java:71)
	at org.obolibrary.robot.OntologyHelper.addAxiomAnnotations(OntologyHelper.java:112)
	at org.obolibrary.robot.AnnotateCommand.execute(AnnotateCommand.java:254)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```
`robot -vvv  annotate -i simple.owl --axiom-annotation rdfs:comment "this is a comment" -o simple_out.owl
`
[simple.zip](https://github.com/ontodev/robot/files/8222076/simple.zip)

Command is iterating through all ontology axioms and trying to add the annotation, but seems we are throwing an exception if axiom is not subClassOf axiom which is inevitable.

https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/OntologyHelper.java#L95

**Comment by matentzn** [comment]
Is this even an approved ROBOT feature? it is not mentioned by the docs, only by the "error messages" in the docs. Maybe this was never fully implemented?

https://robot.obolibrary.org/annotate

You are working on adding the axiom annotations now?

**Comment by hkir-dev** [comment]
I think this exception throwing should be part of the reasoning operation here: https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ReasonOperation.java#L517

not in the Ontology Helper.

This will also help me to use [OntologyHelper#addAxiomAnnotations](https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/OntologyHelper.java#L109) in the scope of this task: https://github.com/ontodev/robot/issues/893#issuecomment-1043223497

Or I can write a separate method that do the same thing without throwing the error.
